@echo off
cd /d "."
echo [HYDRA] Blogger Swarm Atesleniyor...
start /b npx tsx scripts/elite-blogger-autopilot.ts
echo [HYDRA] Tumblr Swarm Atesleniyor...
start /b npx tsx scripts/elite-tumblr-autopilot.ts
echo [HYDRA] GitHub Otorite Köprüsü Kuruluyor...
start /b npx tsx scripts/github-dominator.js
echo [HYDRA] Pinterest Bombardimani Atesleniyor...
start /b npx tsx scripts/elite-pinterest-autopilot.ts
echo [HYDRA] Pinterest Pinger (Force Indexing) Devreye Aliniyor...
start /b npx tsx scripts/pinterest-pinger.js
echo [SUCCESS] Tum motorlar arka planda calisiyor. SALDIRI MODU AKTIF!
