/**
 * 🧛‍♂️ HYDRA SEMANTIC NEIGHBORHOOD MAP
 * Maps Istanbul districts to their closest neighbors for contextual SEO dominance.
 */

export const ISTANBUL_NEIGHBORS: Record<string, string[]> = {
  "adalar": ["Kartal", "Maltepe"],
  "arnavutkoy": ["Başakşehir", "Eyüpsultan"],
  "atasehir": ["Ümraniye", "Kadıköy"],
  "avcilar": ["Beylikdüzü", "Esenyurt"],
  "bagcilar": ["Bahçelievler", "Esenler"],
  "bahcelievler": ["Bakırköy", "Bağcılar"],
  "bakirkoy": ["Bahçelievler", "Zeytinburnu"],
  "basaksehir": ["Arnavutköy", "Sultangazi"],
  "bayrampasa": ["Eyüpsultan", "Esenler"],
  "besiktas": ["Beyoğlu", "Şişli"],
  "beykoz": ["Üsküdar", "Çekmeköy"],
  "beylikduzu": ["Avcılar", "Esenyurt"],
  "beyoglu": ["Beşiktaş", "Şişli"],
  "buyukcekmece": ["Beylikdüzü", "Silivri"],
  "catalca": ["Silivri", "Arnavutköy"],
  "cekmekoy": ["Sancaktepe", "Ümraniye"],
  "esenler": ["Bağcılar", "Bayrampaşa"],
  "esenyurt": ["Beylikdüzü", "Avcılar"],
  "eyupsultan": ["Sarıyer", "Beşiktaş"],
  "fatih": ["Zeytinburnu", "Eyüpsultan"],
  "gaziosmanpasa": ["Sultangazi", "Eyüpsultan"],
  "gungoren": ["Bahçelievler", "Zeytinburnu"],
  "kadikoy": ["Üsküdar", "Ataşehir"],
  "kagithane": ["Şişli", "Eyüpsultan"],
  "kartal": ["Maltepe", "Pendik"],
  "kucukcekmece": ["Sefaköy", "Bakırköy"],
  "maltepe": ["Kartal", "Ataşehir"],
  "pendik": ["Kartal", "Tuzla"],
  "sancaktepe": ["Çekmeköy", "Sultanbeyli"],
  "sariyer": ["Beşiktaş", "Eyüpsultan"],
  "silivri": ["Büyükçekmece", "Çatalca"],
  "sultanbeyli": ["Sancaktepe", "Pendik"],
  "sultangazi": ["Gaziosmanpaşa", "Başakşehir"],
  "sile": ["Çekmeköy", "Beykoz"],
  "sisli": ["Beşiktaş", "Beyoğlu"],
  "tuzla": ["Pendik", "Gebze"],
  "umraniye": ["Ataşehir", "Çekmeköy"],
  "uskudar": ["Kadıköy", "Beykoz"],
  "zeytinburnu": ["Fatih", "Bakırköy"],
  "sefakoy": ["Küçükçekmece", "Bahçelievler"],
  "besyol": ["Florya", "Sefaköy"],
  "ikitelli": ["Başakşehir", "Halkalı"]
};
