/**
 * 🎯 HYDRA FLEET: GA4 MEASUREMENT ID MAP
 * This file is automatically updated by hydra-fleet-auto-provisioner.ts.
 */
export const ga4Mappings: Record<string, string> = {
  "istanbulescort.blog": "G-5N1LVB5EWE",
  "escortvip.net": "G-HL8P9QQDSV",
  "dorukcanay.digital": "G-1KYYJ5TD5Z",
  "vipescorthizmeti.shop": "G-5N1LVB5EWE",
  "test-auto-provision.blog": "G-MX9DWRBZEM",
  "bagcilarescort.shop": "G-DK00KVBP1V",
  "esenyurtescort.blog": "G-2103NRR5Q2",
  "esenyurtescorthizmeti.shop": "G-F18WSN35TZ",
  "beylikduzuescortlistesi.shop": "G-CJ8DB2R3EG",
  "besiktasescorthizmeti.shop": "G-PFW875LE44",
  "besiktasescort.fun": "G-39EKPLXRWP",
  "besiktasescort.blog": "G-PV74J3PFM3",
  "taksimescorthizmeti.shop": "G-NGT9NTY8EE",
  "sefakoyescorthizmeti.shop": "G-HQMVN4TCZY",
  "kucukcekmecescort.shop": "G-GBM8YBPT6F",
  "sisliescort.shop": "G-1GQ2P3SHDK",
  "avrupayakasiescort.shop": "G-XLV6WLQJ23",
  "istanbulescorthizmeti.shop": "G-BPMJVFHS8G",
  "kadikoyescort.shop": "G-PLXTZ99F2F",
  "pendikescorthizmeti.shop": "G-HDS7BPMXWF",
  "bucaescorthizmeti.shop": "G-5RMK91GG6C",
  "izmitescorthizmeti.shop": "G-BV8MF3VD7G",
  "sariyerdrkcnay.shop": "G-JFN786RF5G",
  "leventdrkcnay.shop": "G-8S41HN9VSV",
  "istanbuldrkcnay.shop": "G-RYNG4EXJ0S",
  "istanbulescortkaporasiz.shop": "G-8N0LPT21PD",
  "shopistanbulescortkaporasiz.site": "G-NG1T7V4FNH",
  "escortcoin.space": "G-0DK8LP70ZG",
  "eczane.istanbulescort.blog": "G-0FC46SVN3J",
  "shop.istanbulescort.blog": "G-H7CEM5L7ZP",
  "performans.istanbulescort.blog": "G-KXLESFHEX9",
  "magazinifsa.site": "G-YZ96WVZ2DK",
  "sokhaberifsa.shop": "G-N0GDE8TXVS",
  "dilanpolatifsa.shop": "G-FJK1PD61W9",
  "sansursuzturkifsa.shop": "G-8V8VRYHCEG",
  "exxvideos.shop": "G-V8PM9JER42",
  "telegramifsaizle.shop": "G-BR473ZRPQD",
  "turkifsalar.shop": "G-2X2SLB4J1G",
  "turkifsapremium.shop": "G-61LVYETSJZ",
  "onlyfansizle.shop": "G-BX3QMQ36G4",
  "santajci-tespit.site": "G-T2TWKWWH8G",
  "plakasorgula.shop": "G-Y5HK7YCRYC",
  "casus-yazilim-sil.xyz": "G-98Q15L624L",
  "sanalsms.site": "G-XG34D23WWG",
  "kazandiranborsatuyolari.site": "G-9P2DHDM3D3",
  "tiktokhilesi.sbs": "G-5WZS1YXS4G",
  "bedavahesap.site": "G-8WK08CDZFZ",
  "instacoz.site": "G-HXZ7JESTM2",
  "canlimaclinki.shop": "G-19LJ112BME",
  "kesintisizizle.shop": "G-W3GXTL0T43",
  "fullapkoyun.shop": "G-1R1TXHZB7P",
  "fragmanizle.shop": "G-W47H1EPHXR",
  "konumbulucu.xyz": "G-GSLWYJVLL1",
  "dizicehennemi.site": "G-9KERBV7605",
  "yardimbasvurusu.online": "G-XFYVMNPJ11",
  "vipescorthizmeti.com": "G-F7DFY7GD3S",
  "istanbulescdrkcn.com": "G-YRMW4LQNV2"
};
